#!/usr/bin/env python3
"""
Manual Test Script para la API de Clustering de NYC Taxi Zones
Ejecuta este script en una terminal separada mientras el servidor esté corriendo
"""
import time

def manual_test_instructions():
    print("🧪 PRUEBAS MANUALES DE LA API")
    print("=" * 50)
    print()
    print("✅ EL SERVIDOR ESTÁ CORRIENDO EN: http://localhost:8001")
    print()
    print("🌐 ENDPOINTS DISPONIBLES:")
    print("   1. http://localhost:8001/            - Página principal")
    print("   2. http://localhost:8001/docs        - Documentación Swagger")
    print("   3. http://localhost:8001/health      - Health check")
    print("   4. http://localhost:8001/demo        - Info de clusters demo")
    print("   5. http://localhost:8001/predict     - Predicción (POST)")
    print()
    print("🧪 PRUEBAS RÁPIDAS CON CURL:")
    print()
    print("1️⃣ Test básico:")
    print('   curl http://localhost:8001/')
    print()
    print("2️⃣ Health check:")
    print('   curl http://localhost:8001/health')
    print()
    print("3️⃣ Demo clusters:")
    print('   curl http://localhost:8001/demo')
    print()
    print("4️⃣ Predicción de ejemplo:")
    print('   curl -X POST http://localhost:8001/predict \\')
    print('        -H "Content-Type: application/json" \\')
    print('        -d "{')
    print('          \\"total_trips\\": 1500,')
    print('          \\"avg_pickup_hour\\": 14.5,')
    print('          \\"std_pickup_hour\\": 6.2,')
    print('          \\"peak_hour\\": 18,')
    print('          \\"peak_hour_concentration_pct\\": 8.5,')
    print('          \\"pct_AM_Peak\\": 15.2,')
    print('          \\"pct_PM_Peak\\": 18.7,')
    print('          \\"pct_OP_day\\": 45.3,')
    print('          \\"pct_OP_night\\": 20.8,')
    print('          \\"pct_Early_Morning\\": 5.0,')
    print('          \\"pct_weekend_trips\\": 22.1,')
    print('          \\"avg_trip_distance\\": 2.8,')
    print('          \\"median_trip_distance\\": 1.9,')
    print('          \\"avg_trip_duration\\": 12.5,')
    print('          \\"avg_fare\\": 15.50,')
    print('          \\"avg_total_amount\\": 19.25,')
    print('          \\"avg_tip\\": 2.75,')
    print('          \\"avg_tolls\\": 0.85,')
    print('          \\"pct_yellow_taxi\\": 65.5')
    print('        }"')
    print()
    print("🎯 RESULTADOS ESPERADOS:")
    print("   - Status 200 OK en todos los endpoints")
    print("   - JSON responses con información de clusters")
    print("   - Predicción con cluster ID (0-4) y descripción")
    print()
    print("🚀 TAMBIÉN PUEDES PROBAR EN EL NAVEGADOR:")
    print("   Abre http://localhost:8001/docs para interfaz visual")
    print()
    print("=" * 50)

if __name__ == "__main__":
    manual_test_instructions()
    
    print("\n⏳ Esperando 3 segundos para que puedas ver las instrucciones...")
    time.sleep(3)
    print("\n✅ ¡Listo! Puedes usar estas pruebas mientras el servidor esté corriendo.")
    print("💡 Tip: Abre una nueva terminal para ejecutar los comandos curl")